Repository RIOT-OS/applications, pull requests merged in 2018-10, with the labels that each got.

#45 sniffer: fix default baudrate in script
  sniffer/tools/sniffer.py
Labels: bug, enhancement

#36 sniffer: use fmt instead of printf
  sniffer/Makefile
  sniffer/main.c
  sniffer/tools/sniffer.py
Labels: enhancement

#47 spektrum scanner: adapt to new gnrc_netif calls
  spectrum-scanner/Makefile
  spectrum-scanner/main.c
Labels: enhancement

#49 spektrum-scanner: fix plot_rssi.py script
  spectrum-scanner/tools/plot_rssi.py
Labels: enhancement

#44 coap-chat: a simple chat application using gCoAP
  coap-chat/Makefile
  coap-chat/README.md
  coap-chat/coap.c
  coap-chat/main.c
Labels: new app

#54 sniffer: Check for missing netif header in dump_pkt
  sniffer/main.c
Labels: bug
